#!/bin/bash

if [ -z "$SSL_DOMAIN" ]; then

    echo "You need the SSL_DOMAIN variables"

else

    IFS=',' read -r -a domains <<< "$SSL_DOMAIN"

    if [ -f /etc/letsencrypt/live/${domains[0]}/fullchain.pem ]; then

	

	if /usr/bin/certbot renew
	then
	    /usr/bin/supervisorctl restart nginx
	fi

    else

        echo "Certificate can not be found"

    fi
fi
